[project]
name = "edgettserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "edge-tts>=7.0.0",
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "uvloop>=0.21.0",
]
